DROP TABLE IF EXISTS programmers.ECOLI_DATA;
CREATE TABLE programmers.ECOLI_DATA(
   ID                   INTEGER  NOT NULL PRIMARY KEY
  ,PARENT_ID            INTEGER
  ,SIZE_OF_COLONY       INTEGER  NOT NULL
  ,DIFFERENTIATION_DATE DATE  NOT NULL
  ,GENOTYPE             INTEGER  NOT NULL
);
INSERT INTO programmers.ECOLI_DATA(ID,PARENT_ID,SIZE_OF_COLONY,DIFFERENTIATION_DATE,GENOTYPE) VALUES (1,NULL,10,'2019-01-01',5);
INSERT INTO programmers.ECOLI_DATA(ID,PARENT_ID,SIZE_OF_COLONY,DIFFERENTIATION_DATE,GENOTYPE) VALUES (2,NULL,2,'2019-01-01',3);
INSERT INTO programmers.ECOLI_DATA(ID,PARENT_ID,SIZE_OF_COLONY,DIFFERENTIATION_DATE,GENOTYPE) VALUES (3,2,100,'2020-01-01',4);
INSERT INTO programmers.ECOLI_DATA(ID,PARENT_ID,SIZE_OF_COLONY,DIFFERENTIATION_DATE,GENOTYPE) VALUES (4,2,16,'2020-01-01',4);
INSERT INTO programmers.ECOLI_DATA(ID,PARENT_ID,SIZE_OF_COLONY,DIFFERENTIATION_DATE,GENOTYPE) VALUES (5,2,17,'2020-01-01',6);
INSERT INTO programmers.ECOLI_DATA(ID,PARENT_ID,SIZE_OF_COLONY,DIFFERENTIATION_DATE,GENOTYPE) VALUES (6,4,101,'2021-01-01',22);
INSERT INTO programmers.ECOLI_DATA(ID,PARENT_ID,SIZE_OF_COLONY,DIFFERENTIATION_DATE,GENOTYPE) VALUES (7,4,101,'2022-01-01',23);
INSERT INTO programmers.ECOLI_DATA(ID,PARENT_ID,SIZE_OF_COLONY,DIFFERENTIATION_DATE,GENOTYPE) VALUES (8,6,1,'2022-01-01',27);
