WITH MAX_PRODUCT_PRICE AS (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ("과자", "국", "김치", "식용유")
    GROUP BY CATEGORY
)

SELECT A.CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT AS A JOIN MAX_PRODUCT_PRICE AS B ON A.CATEGORY = B.CATEGORY
WHERE PRICE = MAX_PRICE
ORDER BY MAX_PRICE DESC