SELECT MEMBER_NAME, RC.REVIEW_TEXT, DATE_FORMAT(RC.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE AS MP
    JOIN (
        SELECT MEMBER_ID, REVIEW_TEXT, REVIEW_DATE, COUNT(MEMBER_ID) OVER(PARTITION BY MEMBER_ID) AS REVIEW_COUNT
        FROM REST_REVIEW
        ORDER BY MEMBER_ID) AS RC
    USING(MEMBER_ID)
WHERE REVIEW_COUNT = (
    SELECT COUNT(*) AS COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT DESC
    LIMIT 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT