SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE * SALES) AS TOTAL_SALES
FROM BOOK_SALES AS BS
    JOIN BOOK AS B USING(BOOK_ID)
    JOIN AUTHOR AS A USING(AUTHOR_ID)
WHERE YEAR(SALES_DATE) = "2022" AND MONTH(SALES_DATE) = "1"
GROUP BY AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC