WITH DAILY_RESULT AS (
SELECT *,
    CASE
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN "90일 이상"
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN "30일 이상"
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN "7일 이상"
    END AS DAY_DIFF,
DATEDIFF(END_DATE, START_DATE) + 1 AS RENTAL_DAY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C USING (CAR_ID)
)

SELECT HISTORY_ID,
    ROUND(DAILY_FEE * RENTAL_DAY * (100 - IFNULL(DISCOUNT_RATE, 0)) / 100, 0) AS FEE
FROM DAILY_RESULT A
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON A.CAR_TYPE = P.CAR_TYPE AND A.DAY_DIFF = P.DURATION_TYPE
WHERE A.CAR_TYPE = "트럭"
ORDER BY FEE DESC, HISTORY_ID DESC