WITH TYPE AS (
    SELECT CAR_ID, CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_CAR AS A JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS B USING(CAR_TYPE)
    WHERE DURATION_TYPE = "30일 이상" AND CAR_TYPE IN ("세단", "SUV")
),
RESERVED_RECORD AS (
    SELECT *
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_ID NOT IN (
            SELECT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE (START_DATE BETWEEN "2022-11-01" AND "2022-11-30")
                OR (END_DATE BETWEEN "2022-11-01" AND "2022-11-30")
                OR (START_DATE < "2022-11-01" AND "2022-11-30" < END_DATE)
        )
)

SELECT CAR_ID, R.CAR_TYPE, ROUND(DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100, 0) AS FEE
FROM RESERVED_RECORD AS R JOIN TYPE AS T USING(CAR_ID)
HAVING 500000 <= FEE AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC