WITH FRONTEND AS (
    SELECT SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE CATEGORY = "Front End"
)

SELECT
    CASE
        WHEN (SKILL_CODE & (SELECT CODE FROM FRONTEND)) AND (SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = "Python")) THEN "A"
        WHEN (SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = "C#")) THEN "B"
        WHEN SKILL_CODE & (SELECT CODE FROM FRONTEND) THEN "C"
    END AS GRADE,
    ID, EMAIL
FROM DEVELOPERS AS D
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID