WITH RECURSIVE CTE AS (
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT CHILD.ID, CHILD.PARENT_ID, CTE.GEN + 1
    FROM ECOLI_DATA AS CHILD JOIN CTE ON CHILD.PARENT_ID = CTE.ID
)

SELECT ID
FROM CTE
WHERE GEN = 3