WITH RECURSIVE CTE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM CTE
    WHERE HOUR < 23
)

SELECT HOUR, COUNT(DATETIME) AS COUNT
FROM CTE LEFT JOIN ANIMAL_OUTS AS AO ON CTE.HOUR = HOUR(AO.DATETIME)
GROUP BY HOUR
ORDER BY HOUR