# 2021년에 가입한 전체 회원을 조회
WITH JOINED_TOTAL_USER AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = "2021"
)

SELECT YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT USER_ID) AS PUCHASED_USERS,
    # 2021년에 상품을 구매한 회원 기록 => DISTINCT를 통해서 중복 제거
    ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(USER_ID) FROM JOINED_TOTAL_USER), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (SELECT * FROM JOINED_TOTAL_USER)
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH