WITH MAX_COLONY AS (
    SELECT MAX(SIZE_OF_COLONY) as MAX_SIZE, YEAR(DIFFERENTIATION_DATE) as YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR
)

SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR, B.MAX_SIZE - A.SIZE_OF_COLONY AS YEAR_DEV, A.ID
FROM ECOLI_DATA AS A JOIN MAX_COLONY AS B ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV